[package]
name = "test-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
cfg-if = "1.0.0"
host-wasmi = { path = "../host-wasmi" }
wasi-stub = { path = "../../wasi-stub", optional = true }


[features]
default = []
wasi = ["dep:wasi-stub"]
