[package]
name = "test-runner"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
host-wasmi = { path = "../host-wasmi" }
cfg-if = "1.0.0"


[features]
default = ["abi_unknown"]
abi_unknown = []
abi_wasi = []
