[package]
name = "host-wasmtime"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
wasmtime = { version = "9.0.4", default-features = false, features = [
	"cranelift",
] }
# wasmtime-wasi = { version = "9.0.4", default-features = false }
wasmtime-wasi = "9.0.4"
