[package]
name = "wasi-stub"
edition = "2021"
version = "0.1.0"
authors = ["Arnaud Golfouse <arnaud.golfouse@laposte.net>"]

[dependencies]
wasm-encoder = "0.31.0"
wasmparser = "0.109.0"
thiserror = "1.0"
