[package]
name = "host-rust-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-wasm ={ git = "https://github.com/astrale-sharp/rust-wasm.git"}